from .. import next
next.run1.log()

#失败